### ISSUE TITLE
 Is there a way to skip log in?

### ISSUE THREAD

**Issue by corvusdeinanis** [benji6/moodtracker#157]
Hi! Was wondering how to use this offline. Is there a way to skip logging in?

**Comment by benji6** [comment]
You need to create an account then log in first before you can use it offline. Perhaps this is not clear (in which case I should probably do a better job of explaining that).

As long as you logged in then you can use it offline for extended periods of time and it will sync back to the server whenever you next use it and you have an internet connection.

There is currently no way to use the app without creating an account and logging in first. It would be possible to change the app so you could use it without an account, but it adds some complexity, probably isn't as good of a user experience (no backup and no ability to use across devices) and would require a fair amount of development effort.

Does that answer your question?

**Comment by corvusdeinanis** [comment]
@benji6  It does, thank you so much!
