### ISSUE TITLE
Change/Update Email adress

### ISSUE THREAD

**Issue by olaims** [benji6/moodtracker#182]
Hello, I've tried to find a way to update or change my email address, but I could not find any option.

Do I miss something?

I've also thought about exporting all the data into a .csv or JSON and importing it to my "new" account/email address, but I could not find any "import" option 😔

Thank you!

**Comment by benji6** [comment]
There currently is no way for you to change your email address or to import data. I think this is an important feature though. I can prioritize it and spend some time looking at it over the next few days if you don't mind waiting?

Thanks for raising!

**Comment by olaims** [comment]
Yes, no problem at all!! ☺️

**Comment by benji6** [comment]
@olaims thanks for your patience. I've pushed a feature for changing your email address. You can find it if you go to https://moodtracker.link/settings/change-email (it is also in the menu under Settings). The application will guide you through the process.

Do let me know any other feedback you have and if you run into any trouble let me know here and feel free to re-open the issue.

Thank you very much for raising this!
